# Generated by Django 4.1 on 2022-08-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("simple_excel", "0002_parentmodel_testmodel_delete_siteinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="simple_excel.parentmodel",
            ),
        ),
    ]
